version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrator:
    build: .
    container_name: migrator-container
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      CONFIG_PATH: /root/config/config.yaml
    command: ["./wait-for-postgres.sh", "db", "5432", "--", "./migrator", "--config=/root/config/config.yaml", "--migrations-path=/root/migrations"]
    depends_on:
      - db

  recorder:
    build: .
    container_name: recorder-container
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CONFIG_PATH: /root/config/config.yaml
    ports:
      - "8082:8082"
    command: ["./wait-for-postgres.sh", "db", "5432", "--", "./recorder"]
    depends_on:
      - migrator

volumes:
  pgdata:
    driver: local
