version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: "host"

  migrator:
    build: .
    container_name: migrator-container
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      CONFIG_PATH: /root/config/config.yaml
    command: ["./wait-for-postgres.sh", "localhost", "5432", "--", "./migrator", "--config=/root/config/config.yaml", "--migrations-path=/root/migrations"]
    depends_on:
      - db
    network_mode: "host"

  recorder:
    build: .
    container_name: recorder-container
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CONFIG_PATH: /root/config/config.yaml
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./videos:/root/videos
    command: ["./wait-for-postgres.sh", "localhost", "5432", "--", "./recorder"]
    depends_on:
      - migrator
    network_mode: "host"

volumes:
  pgdata:
    driver: local
