env: "local"
token_ttl: "12h"
secret: "afgjklfadgkjljfdbajklfadggj"
db:
    username: "postgres"
    host: "localhost"
    port: "5432"
    dbname: "postgres"
    sslmode: "disable"

http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 60s

videos_path: "videos"

video_service: "config/opencast.yaml"